version: '2'
services:
    gzhcommittee_server:
        container_name: gzhcommittee_server
        image: gzhcommittee_server
        restart: always
        ports:
            - 3002:3002

    gzhcommittee_serverswagger:
        container_name: gzhcommittee_serverswagger
        image: swaggerapi/swagger-ui
        environment:
            - SWAGGER_JSON=/opt/gzhcommittee_serverswagger/gzhcommittee_serverswagger.yaml
        working_dir: /opt/gzhcommittee_serverswagger/Dapp
        ports:
            - 8082:8080
        volumes:
            - ./gzhcommittee_serverswagger.yaml:/opt/gzhcommittee_serverswagger/gzhcommittee_serverswagger.yaml
