openapi: 3.0.0
servers:
  - url: 'http://52.15.91.107:3003/api/v1'
info:
  description: 投票委员会swagger文档
  version: 0.0.1
  title: Dapp API 文档
tags:
  - name: SSA
    description: ssa相关API
  - name: Member
    description: 成员相关API
  - name: Proposal
    description: 提案相关API
  - name: Auth
    description: 认证相关API

paths:
  #SSA
  /ssa/create:
    post:
      tags:
        - SSA
      summary: 创建ssa
      description: 创建ssa
      security:
        - Bearer: []
      responses:
        '201':
          description: Success
        '401':
          description: UnAuthorized
        '405':
          description: Validation exception
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SSA'
        required: true
  /ssa/support:
    post:
      tags:
        - SSA
      summary: 应援
      description: 创建sssa
      security:
        - Bearer: []
      responses:
        '201':
          description: Success
        '401':
          description: UnAuthorized
        '405':
          description: Validation exception
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSupportRequest'
        required: true
  /ssa/ssa/{id}:
    get:
      tags:
        - SSA
      summary: 查询ssa
      description: 查询ssa
      security:
        - Bearer: []
      parameters:
        - name: id
          in: path
          description: 'The contract id that needs to be fetched.'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: 请求不正确
        '404':
          description: Account not found

  /member/init:
    post:
      tags:
        - Member
      summary: 初始化委员会成员
      description: 使用委员会需要初始化委员会成员
      security:
        - Bearer: []
      responses:
        '201':
          description: Success
        '401':
          description: UnAuthorized
        '405':
          description: Validation exception
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Member'
        required: true
  /member/checkValidity:
    post:
      tags:
        - Member
      summary: 查询委员会成员有效性
      description: 查询委员会成员是否还有效
      security:
        - Bearer: []
      responses:
        '201':
          description: Success
        '401':
          description: UnAuthorized
        '405':
          description: Validation exception
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberValidity'
        required: true
  /member/getAllMember:
    get:
      summary: 获取所有委员会成员
      tags:
        - Member
      description: 获取所有委员会成员
      security:
        - Bearer: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllMemberResponse'
  /proposal/createTx:
    post:
      tags:
        - Proposal
      summary: 创建交易提案
      description: 创建交易提案
      security:
        - Bearer: []
      responses:
        '201':
          description: Success
        '401':
          description: UnAuthorized
        '405':
          description: Validation exception
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTxProposalRequest'
        description: 当前用户创建提案
        required: true
  /proposal/createMem:
    post:
      tags:
        - Proposal
      summary: 创建人员提案
      description: 创建人员提案
      security:
        - Bearer: []
      responses:
        '201':
          description: Success
        '401':
          description: UnAuthorized
        '405':
          description: Validation exception
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMemProposalRequest'
        description: 当前用户创建提案
        required: true
  /proposal/query:
    post:
      tags:
        - Proposal
      summary: 查询提案
      description: 查询提案
      security:
        - Bearer: []
      responses:
        '201':
          description: Success
        '401':
          description: UnAuthorized
        '405':
          description: Validation exception
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryProposalRequest'
        description: 当前用户查询提案
        required: true
  /proposal/voteTx:
    post:
      tags:
        - Proposal
      summary: 交易提案投票
      description: 交易提案投票
      security:
        - Bearer: []
      responses:
        '201':
          description: Success
        '401':
          description: UnAuthorized
        '405':
          description: Validation exception
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoteTxProposalRequest'
        required: true
  /proposal/voteMem:
    post:
      tags:
        - Proposal
      summary: 人员提案投票
      description: 人员提案投票
      security:
        - Bearer: []
      responses:
        '201':
          description: Success
        '401':
          description: UnAuthorized
        '405':
          description: Validation exception
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoteMemProposalRequest'
        required: true
  /proposal/getAllTxProposal:
    get:
      summary: 获取所有交易提案id
      tags:
        - Proposal
      description: 获取所有交易提案id
      security:
        - Bearer: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllProposalResponse'
  /proposal/getAllMemProposal:
    get:
      summary: 获取所有人员提案id
      tags:
        - Proposal
      description: 获取所有人员提案id
      security:
        - Bearer: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllProposalResponse'
  # Auth
  /auth/login:
    post:
      summary: 使用用户名密码登陆，返回JWT token
      description: 登陆
      tags:
        - Auth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: 用户名或密码错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        description: 用户名密码
        required: true
components:
  securitySchemes:
    Bearer:
      type: 'apiKey'
      name: Authorization
      in: header
  schemas:
    ApiResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
        message:
          type: string
          description: ''
        payload:
          type: object
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          description: 用户名
        password:
          type: string
          description: 密码，目前版本密码格式不加validation
    LoginResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          required:
            - payload
          properties:
            payload:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  description: 登陆成功返回的JWT token
    AllMemberResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            payload:
              properties:
                bureaus:
                  type: array
                  items:
                    $ref: '#/components/schemas/MinusMemberuInfo'
    AllTxProposalResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            payload:
              properties:
                bureaus:
                  type: array
                  items:
                    $ref: '#/components/schemas/MinusTxProposalInfo'
    AllMemProposalResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            payload:
              properties:
                bureaus:
                  type: array
                  items:
                    $ref: '#/components/schemas/MinusMemProposalInfo'
    SSA:
      type: object
      properties:
        name:
          type: string
          description: sss名称

    Member:
      type: object
      properties:
        member1:
          type: string
          description: 委员一
        member2:
          type: string
          description: 委员二
        member3:
          type: string
          description: 委员三
        member4:
          type: string
          description: 委员四
        member5:
          type: string
          description: 委员五

    MemberValidity:
      type: object
      properties:
        id:
          type: string
          description: 查询成员id

    MinusMemberuInfo:
      type: object
      properties:
        id: 
          type: string
          description: member id
        validity:
          type: string
          description: member有效性

    MinusTxProposalInfo:
      type: object
      properties:
        id: 
          type: string
          description: proposal id

    MinusMemProposalInfo:
      type: object
      properties:
        id: 
          type: string
          description: proposal id
    QuerySSARequest:
      type: object
      properties:
        id:
          type: string
          description: ssaID
    CreateSupportRequest:
      type: object
      properties:
        ssaID:
          type: string
          description: ssa ID
        amount:
          type: number
          description: 数量
        description:
          type: string
          description: 备注
    CreateTxProposalRequest:
      type: object
      properties:
        ssaID:
          type: string
          description: ssa ID
        amount:
          type: number
          description: 数量
        target:
          type: string
          description: 目标
        deadline:
          type: string
          description: 截止期限
        description:
          type: string
          description: 提案描述
    CreateMemProposalRequest:
      type: object
      properties:
        type:
          type: string
          description: 类型
        member:
          type: string
          description: 目标id
        deadline:
          type: string
          description: 截止期限
        description:
          type: string
          description: 提案描述
    QueryProposalRequest:
      type: object
      properties:
        proposalID:
          type: string
          description: 提案ID
        type:
          type: string
          description: 提案类型
    VoteTxProposalRequest:
      type: object
      properties:
        proposalID:
          type: string
          description: 提案ID
        amount:
          type: number
          description: 投票票数
        choice:
          type: string
          description: 投票决定（y/Y代表同意）
    VoteMemProposalRequest:
      type: object
      properties:
        proposalID:
          type: string
          description: 提案ID
        choice:
          type: string
          description: 投票决定（y/Y代表同意）