openapi: 3.0.0
servers:
  - url: 'http://52.15.91.107:3003/api/v1'
info:
  description: 投票委员会swagger文档
  version: 0.0.1
  title: Dapp API 文档
tags:
  - name: Committee
    description: 委员会相关API
  - name: Member
    description: 成员相关API
  - name: Proposal
    description: 提案相关API
  - name: Auth
    description: 认证相关API

paths:
  #Committee
  /committee/init:
    post:
      tags:
        - Committee
      summary: 初始化委员会
      description: 使用委员会需要初始化委员会
      security:
        - Bearer: []
      responses:
        '200':
          description: Success
        '401':
          description: UnAuthorized
        '400':
          description: Validation exception
        '500':
          description: Error
  /member/init:
    post:
      tags:
        - Member
      summary: 初始化委员会成员
      description: 使用委员会需要初始化委员会成员
      security:
        - Bearer: []
      responses:
        '201':
          description: Success
        '401':
          description: UnAuthorized
        '405':
          description: Validation exception
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Member'
        required: true
  /proposal/create:
    post:
      tags:
        - Proposal
      summary: 创建提案
      description: 创建提案
      security:
        - Bearer: []
      responses:
        '201':
          description: Success
        '401':
          description: UnAuthorized
        '405':
          description: Validation exception
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProposalRequest'
        description: 当前用户创建提案
        required: true
  /proposal/query:
    post:
      tags:
        - Proposal
      summary: 查询提案
      description: 查询提案
      security:
        - Bearer: []
      responses:
        '201':
          description: Success
        '401':
          description: UnAuthorized
        '405':
          description: Validation exception
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryProposalRequest'
        description: 当前用户查询提案
        required: true
  /proposal/vote:
    post:
      tags:
        - Proposal
      summary: 提案投票
      description: 提案投票
      security:
        - Bearer: []
      responses:
        '201':
          description: Success
        '401':
          description: UnAuthorized
        '405':
          description: Validation exception
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoteProposalRequest'
        required: true
  # Auth
  /auth/login:
    post:
      summary: 使用用户名密码登陆，返回JWT token
      description: 登陆
      tags:
        - Auth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: 用户名或密码错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        description: 用户名密码
        required: true
components:
  securitySchemes:
    Bearer:
      type: 'apiKey'
      name: Authorization
      in: header
  schemas:
    ApiResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
        message:
          type: string
          description: ''
        payload:
          type: object
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          description: 用户名
        password:
          type: string
          description: 密码，目前版本密码格式不加validation
    LoginResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          required:
            - payload
          properties:
            payload:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  description: 登陆成功返回的JWT token
    Member:
      type: object
      properties:
        member1:
          type: string
          description: 委员一
        member2:
          type: string
          description: 委员二
        member3:
          type: string
          description: 委员三
        member4:
          type: string
          description: 委员四
        member5:
          type: string
          description: 委员五
    CreateProposalRequest:
      type: object
      properties:
        amount:
          type: number
          description: 数量
        target:
          type: string
          description: 目标
        deadline:
          type: string
          description: 截止期限
        description:
          type: string
          description: 提案描述
    QueryProposalRequest:
      type: object
      properties:
        proposalId:
          type: string
          description: 提案ID
    VoteProposalRequest:
      type: object
      properties:
        proposalId:
          type: string
          description: 提案ID
        choice:
          type: string
          description: 投票决定（y/Y代表同意）